# Generated by Django 2.2.1 on 2019-06-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_load_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Minerals',
            new_name='Mineral',
        ),
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
    ]
